### ISSUE TITLE
新しいパネルのYaml対応

### ISSUE THREAD

**Issue by Suke-H** [Suke-H/kiro_stage_editor#108]
新しいPanelにYamlを対応させる。

```yaml

Height: 1
Width: 7
Cells:
  - - Type: Start
      CellSide: Neutral
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Back
    - Type: Normal
      CellSide: Back
    - Type: Normal
      CellSide: Back
    - Type: Normal
      CellSide: Back
    - Type: Goal
      CellSide: Neutral
Panels:
  - - Type: Normal 
    - Coordinates:
        - X: 0
          Y: 0
        - X: 1
          Y: 0
        - X: 2
          Y: 0
        - X: 3
          Y: 0
  - - Type: Cut
    - Coordinates:
        - X: 0
          Y: 0
        - X: 1
          Y: 0
        - X: 2
          Y: 0
        - X: 3
          Y: 0
```
