### ISSUE TITLE
yaml出力

### ISSUE THREAD

**Issue by Suke-H** [Suke-H/kiro_stage_editor#19]
以下の形式で出力

```yaml
StageRawData:
  Id: 1
  Height: 5
  Width: 5
  Cells:
    - [ { Type: { Type: "N", SkinId: 0 }, StartColor: "White" }, { Type: { Type: "N", SkinId: 0 }, StartColor: "Empty" }, ... ] 
    - [ { Type: { Type: "N", SkinId: 0 }, StartColor: "Black" }, ... ] 
    ...
  Panels:
    - Coordinates:
        - { x: 0, y: 0 }
        - { x: 1, y: 0 }
    - Coordinates:
        - { x: 0, y: 0 }
        - { x: 0, y: 1 }
    
```
