### ISSUE TITLE
📝 yaml形式の変更

### ISSUE THREAD

**Issue by Suke-H** [Suke-H/kiro_stage_editor#28]
## 型変更まわりの修正
- [x] CELL_TYPESの型変更
- [x] gridの型変更
- [x] gridの描画処理変更
- [x] 反転処理変更
- [x] 反転ボタンを追加 
## yamlとURL出力の修正
- [x] yamlの形式変更
- [x] URL共有の処理変更

**Comment by Suke-H** [comment]
こんな感じに変えたい

```yaml
Empty
- label: '空'
- neutral: 
  - code: 'e'
  - picture: 'empty.png'

Normal
- label: '通常床'
- front: 
  - code: 'N'
  - picture: 'white.png'
- back: 
  - code: 'n'
  - picture: 'black.png'

Start
- label: 'スタート'
- neutral: 
  - code: 's'
  - picture: 'start.png'

Goal
- label: 'ゴール'
- neutral:
  - code: 'g'
  - picture: 'goal.png'

DummyGoal
- label: 'ダミーゴール'
- neutral:
  - code: 'd'
  - picture: 'dummyGoal.png'

Crow
- label: 'カラス'
- front:
  - code: 'crow.png'
- back:
  - code: 'black.png'

ArrowUpDown
- label: '矢印↑↓'
- front:
  - code: 'arrowUp.png'
- back:
  - code: 'arroeDown.png'
```

**Comment by Suke-H** [comment]
その際、Gridには以下を渡したい

```yaml
Cell
- type: "Normal"
- side: "front"
```
