### ISSUE TITLE
SkinIDとIdの削除

### ISSUE THREAD

**Issue by qemel** [Suke-H/kiro_stage_editor#44]
## 要望

不要なパラメータになったので削除してほしいです

## From

```yaml
- Id: 0

...

- Type:
    Type: Normal
    SkinId: 0

```

## To

```yaml
(Idは削除)

...

- Type: Normal
```

**Comment by Suke-H** [comment]
こんな感じでよいですかね？
PRしちゃいますね。


```yaml
Height: 4
Width: 4
Cells:
  - - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Goal
      CellSide: Neutral
  - - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
  - - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
  - - Type: Start
      CellSide: Neutral
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
    - Type: Normal
      CellSide: Front
Panels:
  - Coordinates:
      - X: 0
        Y: 0
      - X: 1
        Y: 0
      - X: 0
        Y: 1
      - X: 0
        Y: 2
  - Coordinates:
      - X: 0
        Y: 0
      - X: 1
        Y: 0
      - X: 2
        Y: 0
      - X: 0
        Y: 1
      - X: 1
        Y: 1
      - X: 2
        Y: 1
```

![Image](https://github.com/user-attachments/assets/f69f1e84-dd3e-4dc0-8339-72bc252c0914)
